version: 2.1

orbs:
  circle-compare-url-test: iynere/compare-url@dev:alpha
  circle-compare-url: iynere/compare-url@1.1.0
  cli: circleci/circleci-cli@0.1.2
  orb-tools: circleci/orb-tools@8.13.1
  queue: eddiewebb/queue@1.1.1

jobs:
  trigger-integration:
    executor: orb-tools/alpine
    parameters:
      integration-branch:
        type: enum
        enum: [dev, master]
        default: dev
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints: ["b2:c0:00:a5:2e:87:cf:ac:5b:90:67:85:09:8c:c8:54"]

      - run:
          name: git config
          command: |
            git config --global user.email "$CIRCLE_USERNAME@users.noreply.github.com"
            git config --global user.name "$CIRCLE_USERNAME"

      - run:
          name: trigger integration
          command: |
            if [[ $CIRCLE_BRANCH == "master" ]]; then
              INTEGRATION_BRANCH=integration-<<parameters.integration-branch>>-${CIRCLE_SHA1:0:7}
            else
              INTEGRATION_BRANCH=integration-<<parameters.integration-branch>>-$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7}
            fi

            git checkout -b $INTEGRATION_BRANCH
            git push origin $INTEGRATION_BRANCH

  dev-promote-prod:
    executor: cli/default
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints: ["b2:c0:00:a5:2e:87:cf:ac:5b:90:67:85:09:8c:c8:54"]

      - circle-compare-url/reconstruct:
          debug: true

      - circle-compare-url/use:
          step-name: major release if new commands or jobs, minor if changes to commands or jobs, patch if changes to examples, executors, @orb.yml, otherwise none
          custom-logic: |
            if [[ $(git diff $COMMIT_RANGE --name-status | \
                grep -e "A      src/commands" -e "A      src/jobs") ]]; then
              circleci orb publish promote iynere/compare-url@dev:${CIRCLE_SHA1:0:7} major --token $CIRCLE_TOKEN
            elif [[ $(git diff $COMMIT_RANGE --name-status | \
                grep -e "src/commands" -e "src/jobs") ]]; then
              circleci orb publish promote iynere/compare-url@dev:${CIRCLE_SHA1:0:7} minor --token $CIRCLE_TOKEN
            elif [[ $(git diff $COMMIT_RANGE --name-status | \
                grep -e "src/examples" -e "src/executors" -e "src/@orb.yml") ]]; then
              circleci orb publish promote iynere/compare-url@dev:${CIRCLE_SHA1:0:7} patch --token $CIRCLE_TOKEN
            else
              echo "No changes to orb source; skipping publishing"
            fi

      - run:
          when: always
          name: git config
          command: |
            git config --global user.email "$CIRCLE_USERNAME@users.noreply.github.com"
            git config --global user.name "$CIRCLE_USERNAME"

      - run:
          when: always
          name: cleanup branch
          command: git push origin --delete $CIRCLE_BRANCH


workflows:
  version: 2
  build-and-test:
    jobs:
      - orb-tools/lint:
          filters:
            branches:
              ignore: /integration-.*/

      - orb-tools/pack:
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          context: token
          orb-name: iynere/compare-url
          requires:
            - orb-tools/pack

      - queue/block_workflow:
          consider-branch: false
          requires:
            - orb-tools/publish-dev

      - trigger-integration:
          name: trigger-integration-dev
          context: token
          requires:
            - queue/block_workflow
          filters:
            branches:
              ignore: master

      - trigger-integration:
          name: trigger-integration-master
          context: token
          integration-branch: master
          requires:
            - queue/block_workflow
          filters:
            branches:
              only: master

  integrate-and-deploy:
    jobs:
      - circle-compare-url-test/reconstruct:
          name: check-token-message
          resource-class: small
          debug: true
          filters:
            branches:
              only: /integration-.*/

      - circle-compare-url-test/reconstruct:
          name: integration-test
          context: token
          resource-class: small
          debug: true
          filters:
            branches:
              only: /integration-.*/

          pre-steps:
            - add_ssh_keys:
                fingerprints: ["b2:c0:00:a5:2e:87:cf:ac:5b:90:67:85:09:8c:c8:54"]

          post-steps:
            - run:
                name: copy job output for later comparision
                command: |
                  cp BASE_COMPARE_COMMIT.txt BASE_COMPARE_COMMIT-job.txt
                  cp CIRCLE_COMPARE_URL.txt CIRCLE_COMPARE_URL-job.txt

            - circle-compare-url-test/reconstruct:
                debug: true

            - circle-compare-url/use:
                step-name: copy command output for later comparision
                custom-logic: |
                  mv BASE_COMPARE_COMMIT.txt BASE_COMPARE_COMMIT-command.txt
                  cp CIRCLE_COMPARE_URL.txt CIRCLE_COMPARE_URL-command.txt

            - run:
                name: compare output from job & command
                command: |
                  JOB_BASE_COMMIT=$(cat BASE_COMPARE_COMMIT-job.txt)
                  JOB_COMPARE_URL=$(cat CIRCLE_COMPARE_URL-job.txt)

                  COMMAND_BASE_COMMIT=$(cat BASE_COMPARE_COMMIT-command.txt)
                  COMMAND_COMPARE_URL=$(cat CIRCLE_COMPARE_URL-command.txt)

                  if [[ $JOB_BASE_COMMIT == $COMMAND_BASE_COMMIT && \
                    $JOB_COMPARE_URL == $COMMAND_COMPARE_URL ]]; then
                    echo "job & command output are equal; orb seems to be working as expected"
                  else
                    echo "somehow the values produced by the orb's job and command are not the same; there is probably something wrong with this iteration of the orb"
                    exit 1
                  fi

            - run:
                when: always
                name: git config
                command: |
                  git config --global user.email "$CIRCLE_USERNAME@users.noreply.github.com"
                  git config --global user.name "$CIRCLE_USERNAME"

            - run:
                when: always
                name: cleanup branch
                command: |
                  # remove remote branch, if integration tests were triggered by a non-master-branch commit;
                  # otherwise, remote branch will be removed at the end of the dev-promote-prod job

                  if [[ $(echo $CIRCLE_BRANCH | grep "integration-dev") ]]; then
                    git push origin --delete $CIRCLE_BRANCH
                  fi

      - dev-promote-prod:
          context: token
          requires: [integration-test, check-token-message]
          filters:
            branches:
              only: /integration-master-.*/
